export const currentUser = {
  id: 'user-1',
  username: 'myusername',
  displayName: '디어리',
  avatar: '👤',
  bio: '디데이에 열리는 우리의 편지방',
};

export const users = [
  currentUser,
  {
    id: 'user-2',
    username: 'soyeon_kim',
    displayName: '김소연',
    avatar: '👩',
    bio: '매일 감사하며 살아가요 ✨',
  },
  {
    id: 'user-3',
    username: 'minho_park',
    displayName: '박민호',
    avatar: '👨',
    bio: '커피 좋아하는 개발자',
  },
  {
    id: 'user-4',
    username: 'jieun_lee',
    displayName: '이지은',
    avatar: '👧',
    bio: '여행과 사진을 사랑해요 📸',
  },
  {
    id: 'user-5',
    username: 'daehyun_cho',
    displayName: '조대현',
    avatar: '🧑‍💻',
    bio: '음악이 있는 삶',
  },
  {
    id: 'user-6',
    username: 'yuna_jung',
    displayName: '정유나',
    avatar: '👱‍♀️',
    bio: '책 읽고 글 쓰는 일상',
  },
  {
    id: 'user-7',
    username: 'junho_kang',
    displayName: '강준호',
    avatar: '🧔',
    bio: '운동과 건강한 삶 💪',
  },
  {
    id: 'user-8',
    username: 'haeun_shin',
    displayName: '신하은',
    avatar: '👩‍🎨',
    bio: '그림 그리는 사람',
  },
  {
    id: 'user-9',
    username: 'seungho_lim',
    displayName: '임승호',
    avatar: '👨‍🎓',
    bio: '새로운 것을 배우는 중',
  },
  {
    id: 'user-10',
    username: 'minji_han',
    displayName: '한민지',
    avatar: '👩‍💼',
    bio: '일과 삶의 균형을 찾아서',
  },
  {
    id: 'user-11',
    username: 'taewon_oh',
    displayName: '오태원',
    avatar: '🧑‍🚀',
    bio: '우주를 꿈꾸는 청년',
  },
  {
    id: 'user-12',
    username: 'suhyun_bae',
    displayName: '배수현',
    avatar: '👩‍🏫',
    bio: '아이들과 함께하는 선생님',
  },
  {
    id: 'user-13',
    username: 'donghyuk_son',
    displayName: '손동혁',
    avatar: '👨‍🍳',
    bio: '요리하는 남자',
  },
];

export const friends = [
  {
    id: 'f-1',
    userId: 'user-1',
    friendId: 'user-2',
    friend: users[1],
    status: 'accepted',
    isPinned: true,
  },
  {
    id: 'f-2',
    userId: 'user-1',
    friendId: 'user-3',
    friend: users[2],
    status: 'accepted',
    isPinned: true,
  },
  {
    id: 'f-3',
    userId: 'user-1',
    friendId: 'user-4',
    friend: users[3],
    status: 'accepted',
    isPinned: true,
  },
  {
    id: 'f-4',
    userId: 'user-1',
    friendId: 'user-5',
    friend: users[4],
    status: 'accepted',
    isPinned: true,
  },
  {
    id: 'f-5',
    userId: 'user-1',
    friendId: 'user-6',
    friend: users[5],
    status: 'accepted',
    isPinned: true,
  },
  {
    id: 'f-6',
    userId: 'user-1',
    friendId: 'user-7',
    friend: users[6],
    status: 'accepted',
    isPinned: true,
  },
  {
    id: 'f-7',
    userId: 'user-1',
    friendId: 'user-8',
    friend: users[7],
    status: 'accepted',
    isPinned: true,
  },
  {
    id: 'f-8',
    userId: 'user-1',
    friendId: 'user-9',
    friend: users[8],
    status: 'accepted',
    isPinned: true,
  },
  {
    id: 'f-9',
    userId: 'user-1',
    friendId: 'user-10',
    friend: users[9],
    status: 'accepted',
    isPinned: false,
  },
  {
    id: 'f-10',
    userId: 'user-1',
    friendId: 'user-11',
    friend: users[10],
    status: 'accepted',
    isPinned: false,
  },
  {
    id: 'f-11',
    userId: 'user-1',
    friendId: 'user-12',
    friend: users[11],
    status: 'pending',
    isPinned: false,
  },
  {
    id: 'f-12',
    userId: 'user-1',
    friendId: 'user-13',
    friend: users[12],
    status: 'pending',
    isPinned: false,
  },
];

export function sectionFromDate(date) {
  const m = date.getMonth() + 1;
  const d = date.getDate();
  
  if (m === 1 && d <= 15) return 'new-year';
  if (m >= 2 && m <= 6) return 'mid-1';
  if (m >= 7 && m <= 10) return 'mid-2';
  return 'year-end';
}

export const rooms = [
  {
    id: 'room-1',
    title: '2025를 마무리하며',
    hostId: 'user-1',
    host: currentUser,
    dday: new Date('2025-12-31'),
    visibility: 'friends',
    writePolicy: 'friends',
    openPolicy: 'dday',
    allowAnonymous: true,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/2025-memories',
    coverImage: 'https://images.unsplash.com/photo-1700700736044-1670e04336c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHwyMDI1JTIwbnVtYmVycyUyMGNvbG9yZnVsfGVufDF8fHx8MTc2MjI1MzM4NHww&ixlib=rb-4.1.0&q=80&w=1080',
    year: 2025,
    section: 'year-end',
    participantCount: 12,
    letterCount: 24,
  },
  {
    id: 'room-1b',
    title: '감사의 마음을 담아 💝',
    hostId: 'user-1',
    host: currentUser,
    dday: new Date('2025-11-28'),
    visibility: 'friends',
    writePolicy: 'friends',
    openPolicy: 'dday',
    allowAnonymous: true,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/thanksgiving',
    coverImage: 'https://images.unsplash.com/photo-1586810165699-f4972ac539ff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aGFuayUyMHlvdSUyMGNhcmQlMjBmbG93ZXJzJTIwd29vZHxlbnwxfHx8fDE3NjIyNTMzODV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    year: 2025,
    section: 'year-end',
    participantCount: 8,
    letterCount: 15,
  },
  {
    id: 'room-1c',
    title: '소연아 생일 축하해! 🎉',
    hostId: 'user-1',
    host: currentUser,
    dday: new Date('2025-11-10'),
    visibility: 'friends',
    writePolicy: 'friends',
    openPolicy: 'dday',
    allowAnonymous: true,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/soyeon-bday',
    coverImage: 'https://images.unsplash.com/photo-1761253298457-d98f628e1b1f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiaXJ0aGRheSUyMGJhbGxvb25zJTIwY29sb3JmdWx8ZW58MXx8fHwxNzYyMjUzMzg1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    year: 2025,
    section: 'year-end',
    participantCount: 12,
    letterCount: 24,
  },
  {
    id: 'room-1d',
    title: '가을 소풍 기억해? 🍂',
    hostId: 'user-1',
    host: currentUser,
    dday: new Date('2025-10-15'),
    visibility: 'friends',
    writePolicy: 'friends',
    openPolicy: 'dday',
    allowAnonymous: true,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/autumn-picnic',
    coverImage: 'https://images.unsplash.com/photo-1697714753811-63da503a57d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhdXR1bW4lMjBmbG93ZXJzJTIwZmFsbCUyMGxlYXZlc3xlbnwxfHx8fDE3NjIyNTMzODZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    year: 2025,
    section: 'mid-2',
    participantCount: 6,
    letterCount: 12,
  },
  {
    id: 'room-1e',
    title: '우리의 여름 추억',
    hostId: 'user-1',
    host: currentUser,
    dday: new Date('2025-08-20'),
    visibility: 'friends',
    writePolicy: 'friends',
    openPolicy: 'dday',
    allowAnonymous: false,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/summer-memories',
    coverImage: 'https://images.unsplash.com/photo-1627589611543-e26e85101322?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZWFjaCUyMGNoYWlycyUyMG9jZWFuJTIwc3VtbWVyfGVufDF8fHx8MTc2MjI1MzM4Nnww&ixlib=rb-4.1.0&q=80&w=1080',
    year: 2025,
    section: 'mid-2',
    participantCount: 5,
    letterCount: 10,
  },
  {
    id: 'room-1f',
    title: '우리 팀 화이팅! 💪',
    hostId: 'user-1',
    host: currentUser,
    dday: new Date('2025-07-01'),
    visibility: 'friends',
    writePolicy: 'invite',
    openPolicy: 'dday',
    allowAnonymous: false,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/team-fighting',
    coverImage: 'https://images.unsplash.com/photo-1630672790237-38eeb57cb60b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZWFtJTIwd29yayUyMG1lZXRpbmclMjBvZmZpY2V8ZW58MXx8fHwxNzYyMjUzMzg3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    year: 2025,
    section: 'mid-2',
    participantCount: 8,
    letterCount: 16,
  },
  {
    id: 'room-1g',
    title: '힐링타임 ☕',
    hostId: 'user-1',
    host: currentUser,
    dday: new Date('2025-05-20'),
    visibility: 'friends',
    writePolicy: 'friends',
    openPolicy: 'dday',
    allowAnonymous: true,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/healing-time',
    coverImage: 'https://images.unsplash.com/photo-1589272423304-35786c38ce2b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYXN0ZWwlMjBwaW5rJTIwYWVzdGhldGljfGVufDF8fHx8MTc2MjIyNzM5N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    year: 2025,
    section: 'mid-1',
    participantCount: 4,
    letterCount: 8,
  },
  {
    id: 'room-1h',
    title: '생일파티 🎂',
    hostId: 'user-1',
    host: currentUser,
    dday: new Date('2025-04-12'),
    visibility: 'friends',
    writePolicy: 'friends',
    openPolicy: 'dday',
    allowAnonymous: true,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/birthday-party',
    coverImage: 'https://images.unsplash.com/photo-1759124650346-43900f8479d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYXJ0eSUyMGNlbGVicmF0aW9uJTIwZGVjb3JhdGlvbnN8ZW58MXx8fHwxNzYyMTY4NTIyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    year: 2025,
    section: 'mid-1',
    participantCount: 15,
    letterCount: 28,
  },
  {
    id: 'room-1i',
    title: '결혼 축하해요! 💐',
    hostId: 'user-1',
    host: currentUser,
    dday: new Date('2025-03-22'),
    visibility: 'friends',
    writePolicy: 'friends',
    openPolicy: 'dday',
    allowAnonymous: false,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/wedding',
    coverImage: 'https://images.unsplash.com/photo-1631998878375-236a6826ce7f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3ZWRkaW5nJTIwY2FrZSUyMGZsb3dlcnN8ZW58MXx8fHwxNzYyMjUzMzg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    year: 2025,
    section: 'mid-1',
    participantCount: 32,
    letterCount: 58,
  },
  {
    id: 'room-2',
    title: '민호야 취업 축하해! 🎉',
    hostId: 'user-4',
    host: users[3],
    dday: new Date('2025-01-10'),
    visibility: 'friends',
    writePolicy: 'invite',
    openPolicy: 'instant',
    allowAnonymous: false,
    allowOneToOne: true,
    shareUrl: 'https://pyeonjibang.com/r/minho-job',
    coverImage: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800',
    year: 2025,
    section: 'new-year',
    participantCount: 8,
    letterCount: 15,
  },
  {
    id: 'room-3',
    title: '메리 크리스마스 🎄',
    hostId: 'user-3',
    host: users[2],
    dday: new Date('2024-12-25'),
    visibility: 'public',
    writePolicy: 'all',
    openPolicy: 'dday',
    allowAnonymous: true,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/xmas-2024',
    coverImage: 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=800',
    year: 2024,
    section: 'year-end',
    participantCount: 45,
    letterCount: 102,
  },
  {
    id: 'room-4',
    title: '지은이 졸업 축하 💐',
    hostId: 'user-1',
    host: currentUser,
    dday: new Date('2025-02-20'),
    visibility: 'friends',
    writePolicy: 'friends',
    openPolicy: 'dday',
    allowAnonymous: false,
    allowOneToOne: true,
    shareUrl: 'https://pyeonjibang.com/r/jieun-grad',
    year: 2025,
    section: 'mid-1',
    participantCount: 18,
    letterCount: 32,
  },
  {
    id: 'room-5',
    title: '2025 새해 복 많이 받으세요 🎊',
    hostId: 'user-5',
    host: users[4],
    dday: new Date('2025-01-01'),
    visibility: 'public',
    writePolicy: 'all',
    openPolicy: 'instant',
    allowAnonymous: true,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/newyear-2025',
    coverImage: 'https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=800',
    year: 2025,
    section: 'new-year',
    participantCount: 67,
    letterCount: 134,
  },
  {
    id: 'room-6',
    title: '유나의 첫 전시회 축하 🎨',
    hostId: 'user-6',
    host: users[5],
    dday: new Date('2025-04-05'),
    visibility: 'friends',
    writePolicy: 'friends',
    openPolicy: 'dday',
    allowAnonymous: false,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/yuna-exhibition',
    coverImage: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800',
    year: 2025,
    section: 'mid-1',
    participantCount: 23,
    letterCount: 41,
  },
  {
    id: 'room-7',
    title: '준호 마라톤 완주 축하! 🏃',
    hostId: 'user-7',
    host: users[6],
    dday: new Date('2025-05-18'),
    visibility: 'friends',
    writePolicy: 'invite',
    openPolicy: 'instant',
    allowAnonymous: false,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/junho-marathon',
    year: 2025,
    section: 'mid-1',
    participantCount: 6,
    letterCount: 9,
  },
  {
    id: 'room-8',
    title: '우리 팀 프로젝트 성공 🚀',
    hostId: 'user-8',
    host: users[7],
    dday: new Date('2025-06-30'),
    visibility: 'friends',
    writePolicy: 'invite',
    openPolicy: 'dday',
    allowAnonymous: true,
    allowOneToOne: true,
    shareUrl: 'https://pyeonjibang.com/r/team-success',
    coverImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800',
    year: 2025,
    section: 'mid-1',
    participantCount: 5,
    letterCount: 12,
  },
  {
    id: 'room-9',
    title: '승호 대학원 합격 축하 🎓',
    hostId: 'user-9',
    host: users[8],
    dday: new Date('2025-01-25'),
    visibility: 'friends',
    writePolicy: 'friends',
    openPolicy: 'dday',
    allowAnonymous: false,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/seungho-grad-school',
    year: 2025,
    section: 'new-year',
    participantCount: 14,
    letterCount: 26,
  },
  {
    id: 'room-10',
    title: '민지 이직 축하해요! 🌟',
    hostId: 'user-10',
    host: users[9],
    dday: new Date('2025-02-01'),
    visibility: 'friends',
    writePolicy: 'invite',
    openPolicy: 'instant',
    allowAnonymous: true,
    allowOneToOne: true,
    shareUrl: 'https://pyeonjibang.com/r/minji-new-job',
    year: 2025,
    section: 'mid-1',
    participantCount: 11,
    letterCount: 19,
  },
  {
    id: 'room-11',
    title: '제주도 여행 추억 🌴',
    hostId: 'user-1',
    host: currentUser,
    dday: new Date('2025-08-20'),
    visibility: 'friends',
    writePolicy: 'invite',
    openPolicy: 'dday',
    allowAnonymous: false,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/jeju-trip',
    coverImage: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    year: 2025,
    section: 'mid-2',
    participantCount: 4,
    letterCount: 8,
  },
  {
    id: 'room-12',
    title: '태원이 생일 파티 🎈',
    hostId: 'user-11',
    host: users[10],
    dday: new Date('2025-07-12'),
    visibility: 'friends',
    writePolicy: 'friends',
    openPolicy: 'dday',
    allowAnonymous: true,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/taewon-bday',
    year: 2025,
    section: 'mid-2',
    participantCount: 16,
    letterCount: 28,
  },
  {
    id: 'room-13',
    title: '수현 선생님 감사합니다 🌻',
    hostId: 'user-12',
    host: users[11],
    dday: new Date('2025-05-15'),
    visibility: 'friends',
    writePolicy: 'all',
    openPolicy: 'dday',
    allowAnonymous: true,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/teacher-appreciation',
    coverImage: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800',
    year: 2025,
    section: 'mid-1',
    participantCount: 31,
    letterCount: 58,
  },
  {
    id: 'room-14',
    title: '동혁이 레스토랑 오픈 축하 🍽️',
    hostId: 'user-13',
    host: users[12],
    dday: new Date('2025-03-01'),
    visibility: 'public',
    writePolicy: 'all',
    openPolicy: 'instant',
    allowAnonymous: false,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/restaurant-opening',
    coverImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    year: 2025,
    section: 'mid-1',
    participantCount: 42,
    letterCount: 67,
  },
  {
    id: 'room-15',
    title: '우리 회사 10주년 🎊',
    hostId: 'user-3',
    host: users[2],
    dday: new Date('2025-09-10'),
    visibility: 'friends',
    writePolicy: 'invite',
    openPolicy: 'dday',
    allowAnonymous: false,
    allowOneToOne: false,
    shareUrl: 'https://pyeonjibang.com/r/company-10years',
    coverImage: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800',
    year: 2025,
    section: 'mid-2',
    participantCount: 28,
    letterCount: 52,
  },
];

export const letters = [
  // Room 1: 소연이 생일
  {
    id: 'letter-1',
    roomId: 'room-1',
    senderId: 'user-3',
    sender: users[2],
    receiverId: 'user-2',
    receiver: users[1],
    year: 2025,
    section: 'mid-1',
    dday: new Date('2025-03-15'),
    visibleFrom: new Date('2025-03-15'),
    content: '소연아! 생일 정말 축하해 🎂 항상 밝은 모습으로 우리 팀 분위기 메이커 역할 해줘서 고마워. 올 한 해도 건강하고 행복한 일만 가득하길 바랄게!',
    isAnon: false,
    createdAt: new Date('2025-03-10'),
    font: 'Noto Serif KR',
    letterPaper: 'dotted',
    categories: ['birthday'],
  },
  {
    id: 'letter-2',
    roomId: 'room-1',
    senderId: 'user-4',
    sender: users[3],
    receiverId: 'user-2',
    receiver: users[1],
    year: 2025,
    section: 'mid-1',
    dday: new Date('2025-03-15'),
    visibleFrom: new Date('2025-03-15'),
    content: '생일 축하해요 소연씨! 같이 일하면서 많이 배우고 있어요. 항상 꼼꼼하고 세심한 모습 존경합니다 ✨',
    isAnon: false,
    createdAt: new Date('2025-03-12'),
    font: 'Gowun Batang',
    letterPaper: 'lined',
    categories: ['birthday'],
  },
  {
    id: 'letter-3',
    roomId: 'room-1',
    senderId: undefined,
    sender: undefined,
    receiverId: 'user-2',
    receiver: users[1],
    year: 2025,
    section: 'mid-1',
    dday: new Date('2025-03-15'),
    visibleFrom: new Date('2025-03-15'),
    content: '소연아 생일 축하해! 늘 응원하고 있어 💕',
    isAnon: true,
    createdAt: new Date('2025-03-11'),
    font: 'Nanum Gothic',
    letterPaper: 'plain',
    categories: ['birthday', 'anonymous'],
  },
  
  // Room 2: 민호 취업 축하
  {
    id: 'letter-4',
    roomId: 'room-2',
    senderId: 'user-1',
    sender: currentUser,
    receiverId: 'user-3',
    receiver: users[2],
    year: 2025,
    section: 'new-year',
    dday: new Date('2025-01-10'),
    visibleFrom: new Date('2025-01-10'),
    content: '민호야 취업 진심으로 축하해! 네가 얼마나 열심히 준비했는지 다 알고 있어. 새로운 회사에서도 멋지게 활약할 거라 믿어 의심치 않아 🎉',
    isAnon: false,
    createdAt: new Date('2025-01-08'),
    font: 'Noto Sans KR',
    letterPaper: 'plain',
    categories: [],
  },
  {
    id: 'letter-5',
    roomId: 'room-2',
    senderId: 'user-5',
    sender: users[4],
    receiverId: 'user-3',
    receiver: users[2],
    year: 2025,
    section: 'new-year',
    dday: new Date('2025-01-10'),
    visibleFrom: new Date('2025-01-10'),
    content: '축하해 민호! 항상 성실하게 노력하는 모습 보기 좋았어. 새로운 직장에서도 그 열정 잃지 마! 화이팅 💪',
    isAnon: false,
    createdAt: new Date('2025-01-09'),
    font: 'Gowun Dodum',
    letterPaper: 'dotted',
    categories: [],
  },
  
  // Room 3: 크리스마스
  {
    id: 'letter-6',
    roomId: 'room-3',
    senderId: 'user-1',
    sender: currentUser,
    receiverId: undefined,
    receiver: undefined,
    year: 2024,
    section: 'year-end',
    dday: new Date('2024-12-25'),
    visibleFrom: new Date('2024-12-25'),
    content: '모두에게 따뜻하고 행복한 크리스마스 되시길 바랍니다! 올 한 해 수고 많으셨어요 🎄❤️',
    isAnon: false,
    createdAt: new Date('2024-12-20'),
    font: 'Nanum Myeongjo',
    letterPaper: 'plain',
    categories: ['year-end'],
  },
  {
    id: 'letter-7',
    roomId: 'room-3',
    senderId: undefined,
    sender: undefined,
    receiverId: undefined,
    receiver: undefined,
    year: 2024,
    section: 'year-end',
    dday: new Date('2024-12-25'),
    visibleFrom: new Date('2024-12-25'),
    content: '메리 크리스마스! 모두 사랑하는 사람들과 행복한 시간 보내세요 🎅🎁',
    isAnon: true,
    createdAt: new Date('2024-12-22'),
    font: 'Noto Serif KR',
    letterPaper: 'lined',
    categories: ['year-end', 'anonymous'],
  },
  
  // Room 4: 지은이 졸업
  {
    id: 'letter-8',
    roomId: 'room-4',
    senderId: 'user-6',
    sender: users[5],
    receiverId: 'user-4',
    receiver: users[3],
    year: 2025,
    section: 'mid-1',
    dday: new Date('2025-02-20'),
    visibleFrom: new Date('2025-02-20'),
    content: '지은아 졸업 축하해! 대학 생활 동안 정말 열심히 살았잖아. 앞으로의 인생도 지금처럼 빛나길! 💐',
    isAnon: false,
    createdAt: new Date('2025-02-15'),
    font: 'Gowun Batang',
    letterPaper: 'dotted',
    categories: [],
  },
  {
    id: 'letter-9',
    roomId: 'room-4',
    senderId: 'user-7',
    sender: users[6],
    receiverId: 'user-4',
    receiver: users[3],
    year: 2025,
    section: 'mid-1',
    dday: new Date('2025-02-20'),
    visibleFrom: new Date('2025-02-20'),
    content: '지은씨 졸업 진심으로 축하드려요. 학교에서 만난 가장 열정적인 사람이었어요. 새로운 시작도 응원합니다! 🎓',
    isAnon: false,
    createdAt: new Date('2025-02-18'),
    font: 'Nanum Gothic',
    letterPaper: 'plain',
    categories: [],
  },
  
  // Room 5: 새해 복
  {
    id: 'letter-10',
    roomId: 'room-5',
    senderId: 'user-2',
    sender: users[1],
    receiverId: undefined,
    receiver: undefined,
    year: 2025,
    section: 'new-year',
    dday: new Date('2025-01-01'),
    visibleFrom: new Date('2025-01-01'),
    content: '2025년 새해 복 많이 받으세요! 모두의 소원이 이루어지는 한 해가 되길 바랍니다 🎊✨',
    isAnon: false,
    createdAt: new Date('2024-12-30'),
    font: 'Noto Sans KR',
    letterPaper: 'lined',
    categories: ['new-year'],
  },
  {
    id: 'letter-11',
    roomId: 'room-5',
    senderId: undefined,
    sender: undefined,
    receiverId: undefined,
    receiver: undefined,
    year: 2025,
    section: 'new-year',
    dday: new Date('2025-01-01'),
    visibleFrom: new Date('2025-01-01'),
    content: '새해에는 건강하고 행복한 일만 가득하시길! Happy New Year! 🎉',
    isAnon: true,
    createdAt: new Date('2024-12-31'),
    font: 'Gowun Dodum',
    letterPaper: 'plain',
    categories: ['new-year', 'anonymous'],
  },
];

export const getSectionName = (section) => {
  switch (section) {
    case 'new-year':
      return '신년';
    case 'mid-1':
      return '상반기/생일';
    case 'mid-2':
      return '하반기/생일';
    case 'year-end':
      return '연말';
    default:
      return '';
  }
};

export const getVisibilityLabel = (visibility) => {
  switch (visibility) {
    case 'public':
      return 'PUBLIC';
    case 'friends':
      return 'FRIENDS';
    case 'private':
      return 'PRIVATE';
    default:
      return '';
  }
};

export const getDaysUntil = (date) => {
  const now = new Date();
  const diff = date.getTime() - now.getTime();
  return Math.ceil(diff / (1000 * 60 * 60 * 24));
};

export const isVisible = (letter) => {
  return new Date() >= letter.visibleFrom;
};

// Notices data
export const notices = [
  {
    id: 'notice-1',
    title: '🎉 편지방 서비스 오픈!',
    content: '안녕하세요! 편지방 서비스가 정식으로 오픈했습니다.\\n\\n디데이에 열리는 특별한 추억을 소중한 사람들과 함께 나눠보세요.\\n공개 범위, 작성 권한, 익명 허용 등 다양한 설정을 통해 나만의 편지방을 만들어보실 수 있어요.\\n\\n앞으로도 더 좋은 서비스로 찾아뵙겠습니다. 감사합니다! ❤️',
    category: 'event',
    createdAt: new Date('2025-01-01T10:00:00'),
  },
  {
    id: 'notice-2',
    title: '새로운 편지지 디자인 추가',
    content: '새로운 편지지 디자인이 추가되었어요! 🎨\\n\\n이제 더 다양한 편지지로 나만의 편지를 꾸며보세요.\\n- 도트 편지지\\n- 줄 편지지\\n- 플레인 편지지\\n\\n편지 작성 시 편지지 선택 버튼을 눌러서 원하는 디자인을 선택할 수 있어요.',
    category: 'update',
    createdAt: new Date('2025-01-15T14:30:00'),
  },
  {
    id: 'notice-3',
    title: '서버 점검 안내',
    content: '안녕하세요, 편지방 팀입니다.\\n\\n더 나은 서비스 제공을 위해 서버 점검을 진행할 예정입니다.\\n\\n일시: 2025년 2월 1일 새벽 2시 ~ 4시 (약 2시간)\\n점검 내용: 서버 안정화 및 성능 개선\\n\\n점검 시간 동안 서비스 이용이 일시적으로 중단될 수 있습니다.\\n이용에 불편을 드려 죄송합니다.',
    category: 'maintenance',
    createdAt: new Date('2025-01-28T09:00:00'),
  },
  {
    id: 'notice-4',
    title: '폰트 선택 기능 업데이트',
    content: '편지 작성 시 다양한 폰트를 선택할 수 있게 되었어요! ✨\\n\\n지원 폰트:\\n- Noto Sans KR\\n- Noto Serif KR\\n- Gowun Batang\\n- Gowun Dodum\\n- Nanum Gothic\\n- Nanum Myeongjo\\n\\n편지 작성 화면에서 폰트 버튼을 눌러 원하는 폰트를 선택해보세요.',
    category: 'update',
    createdAt: new Date('2025-02-10T16:00:00'),
  },
  {
    id: 'notice-5',
    title: '개인정보 처리방침 업데이트',
    content: '편지방의 개인정보 처리방침이 업데이트되었습니다.\\n\\n주요 변경 사항:\\n- 데이터 보관 기간 명시\\n- 제3자 정보 제공 항목 추가\\n- 이용자 권리 안내 강화\\n\\n자세한 내용은 설정 > 개인정보 처리방침에서 확인하실 수 있습니다.',
    category: 'general',
    createdAt: new Date('2025-02-20T11:00:00'),
  },
];